#Scott Smith
#Poker Stats Page

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QHeaderView, QTableWidget, QAbstractItemView, QMainWindow, QTableWidgetItem 
#import time
import datetime
#from PokerDB import *



class Ui_Form(QMainWindow):

    def __init__(self, con, connected, username):
        self.con = con
        self.connected = connected
        self.username = username 
        super().__init__()
        self.setStyleSheet("QMainWindow {background-image: url(images/stats.png);}")
        self.setWindowIcon(QtGui.QIcon('images/icon.png'))

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 800)

        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(57, 230, 886, 60))
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setAutoScrollMargin(16)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget.verticalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.tableWidget.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.tableWidget.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidget.setFocusPolicy(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget_2 = QtWidgets.QTableWidget(Form)
        self.tableWidget_2.setGeometry(QtCore.QRect(70, 330, 240, 370))
        self.tableWidget_2.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_2.verticalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.tableWidget_2.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.tableWidget_2.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidget_2.setFocusPolicy(0)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(1)
        self.tableWidget_2.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        self.tableWidget_3 = QtWidgets.QTableWidget(Form)
        self.tableWidget_3.setGeometry(QtCore.QRect(380, 330, 240, 370))
        self.tableWidget_3.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_3.verticalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.tableWidget_3.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.tableWidget_3.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidget_3.setFocusPolicy(0)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(1)
        self.tableWidget_3.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        self.tableWidget_4 = QtWidgets.QTableWidget(Form)
        self.tableWidget_4.setGeometry(QtCore.QRect(665, 330, 290, 370))
        self.tableWidget_4.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_4.verticalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.tableWidget_4.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.tableWidget_4.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidget_4.setFocusPolicy(0)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(1)
        self.tableWidget_4.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(300, 50, 400, 100))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        #self.label_6.setFont(font)
        #self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setScaledContents(False)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_6.setStyleSheet("background-image: url(images/logopurp.png);")

        #self.label_7 = QtWidgets.QLabel(Form)
        #self.label_7.setEnabled(True)
        #self.label_7.setGeometry(QtCore.QRect(311, 100, 378, 23))
        #self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        #self.label_7.setObjectName("label_7")
        
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(422, 150, 156, 66))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_10.setStyleSheet("background-image: url(images/stats_border.png);")

        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(100, 70, 72, 96))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/blue.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(828, 70, 72, 96))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("images/red.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Statistics"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Player Number"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Deck Color"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Score"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Hands Played"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Hands Won"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Time Played"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("Form", "Pair"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("Form", "Two Pair"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("Form", "Three of a Kind"))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("Form", "Straight"))
        item = self.tableWidget_2.verticalHeaderItem(4)
        item.setText(_translate("Form", "Flush"))
        item = self.tableWidget_2.verticalHeaderItem(5)
        item.setText(_translate("Form", "Full House"))
        item = self.tableWidget_2.verticalHeaderItem(6)
        item.setText(_translate("Form", "Four of a Kind"))
        item = self.tableWidget_2.verticalHeaderItem(7)
        item.setText(_translate("Form", "Straight Flush"))
        item = self.tableWidget_2.verticalHeaderItem(8)
        item.setText(_translate("Form", "Royal Flush"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Player Stats"))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("Form", "Pair"))
        item = self.tableWidget_3.verticalHeaderItem(1)
        item.setText(_translate("Form", "Two Pair"))
        item = self.tableWidget_3.verticalHeaderItem(2)
        item.setText(_translate("Form", "Three of a Kind"))
        item = self.tableWidget_3.verticalHeaderItem(3)
        item.setText(_translate("Form", "Straight"))
        item = self.tableWidget_3.verticalHeaderItem(4)
        item.setText(_translate("Form", "Flush"))
        item = self.tableWidget_3.verticalHeaderItem(5)
        item.setText(_translate("Form", "Full House"))
        item = self.tableWidget_3.verticalHeaderItem(6)
        item.setText(_translate("Form", "Four of a Kind"))
        item = self.tableWidget_3.verticalHeaderItem(7)
        item.setText(_translate("Form", "Straight Flush"))
        item = self.tableWidget_3.verticalHeaderItem(8)
        item.setText(_translate("Form", "Royal Flush"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Global Stats"))
        item = self.tableWidget_4.verticalHeaderItem(0)
        item.setText(_translate("Form", "1st"))
        item = self.tableWidget_4.verticalHeaderItem(1)
        item.setText(_translate("Form", "2nd"))
        item = self.tableWidget_4.verticalHeaderItem(2)
        item.setText(_translate("Form", "3rd"))
        item = self.tableWidget_4.verticalHeaderItem(3)
        item.setText(_translate("Form", "4th"))
        item = self.tableWidget_4.verticalHeaderItem(4)
        item.setText(_translate("Form", "5th"))
        item = self.tableWidget_4.verticalHeaderItem(5)
        item.setText(_translate("Form", "6th"))
        item = self.tableWidget_4.verticalHeaderItem(6)
        item.setText(_translate("Form", "7th"))
        item = self.tableWidget_4.verticalHeaderItem(7)
        item.setText(_translate("Form", "8th"))
        item = self.tableWidget_4.verticalHeaderItem(8)
        item.setText(_translate("Form", "9th"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("Form", "High Scores"))
        #self.label_6.setText(_translate("Form", "Poker Game"))
        #self.label_7.setText(_translate("Form", "By Scott Smith"))
        self.label_10.setText(_translate("Form", "General Statistics"))
                # ----------------- EXTRACT ALL DB INFO HERE ----------------------
        self.loadData()

    def loadData(self):

        if self.connected and self.username != None:
            with self.con:
                cur = self.con.cursor()

                query = "SELECT * FROM users WHERE username = %s;"
                cur.execute(query, (self.username))
                rs = cur.fetchall()
                
                
                        #----------------------          LOAD PLAYER INFO HERE                      -----------------------
                for i in range(8):
                        #shows an icon for deck color; makes it look pretty
                    if i == 3:
                        label = QtWidgets.QLabel()
                        pix = QtGui.QPixmap("images/" + rs[0][i] + ".png")
                        resPix = pix.scaled(28, 28, QtCore.Qt.IgnoreAspectRatio, QtCore.Qt.SmoothTransformation)
                        label.setPixmap(resPix)
                        label.setAlignment(QtCore.Qt.AlignCenter)
                        self.tableWidget.setCellWidget(0, i - 1, label)
                        continue
                        
                    else:
                            #convert seconds to hh:mm:ss format for time played  
                        if i == 7:
                            item = QTableWidgetItem()
                            font = QtGui.QFont()
                            font.setFamily("Consolas")
                            item.setFont(font)
                            item.setTextAlignment(QtCore.Qt.AlignCenter)
                            seconds = rs[0][i]
                            item.setText(str(datetime.timedelta(seconds = seconds)))
                            self.tableWidget.setItem(0, i - 1, item)
                            continue

                        else:
                            #skip password here
                            if i == 2:
                                continue
                            else:         
                                item = QTableWidgetItem()
                                font = QtGui.QFont()
                                font.setFamily("Consolas")
                                item.setFont(font)
                                item.setTextAlignment(QtCore.Qt.AlignCenter)
                                item.setText(str(rs[0][i]))
                    if i < 2:
                        self.tableWidget.setItem(0, i, item)
                    else:     
                        self.tableWidget.setItem(0, i - 1, item)

                #   ------------------- LOAD PLAYER HAND RANKS HERE ----------------------
                    #j is start index in db
                j = 8
                for i in range(9):
                    item = QTableWidgetItem()
                    font = QtGui.QFont()
                    font.setFamily("Consolas")
                    item.setFont(font)
                    item.setTextAlignment(QtCore.Qt.AlignCenter)
                    item.setText(str(rs[0][j]))
                    self.tableWidget_2.setItem(i, 0, item)
                    j += 1

                # --------------------- LOAD GLOBAL HAND RANKS HERE ----------------------

                query = "SELECT * FROM users WHERE user_id = 1;"
                cur.execute(query)
                rs = cur.fetchall()

                j = 8
                for i in range(9):
                    item = QTableWidgetItem()
                    font = QtGui.QFont()
                    font.setFamily("Consolas")
                    item.setFont(font)
                    item.setTextAlignment(QtCore.Qt.AlignCenter)
                    item.setText(str(rs[0][j]))
                    self.tableWidget_3.setItem(i, 0, item)
                    j += 1            

                # ---------------------- LOAD HIGH SCORE LIST HERE ----------------------------

                query = "SELECT username, score FROM users WHERE user_id <> 1 ORDER BY score DESC LIMIT 9;"
                cur.execute(query)
                rs = cur.fetchall()
                for i in range(len(rs)):
                    item = QTableWidgetItem()
                    font = QtGui.QFont()
                    font.setFamily("Consolas")
                    item.setFont(font)
                    item.setText("%-20s%10s" % (rs[i][0], str(rs[i][1])))
                    self.tableWidget_4.setItem(i, 0, item)         

'''
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    
    #establish DB connection 
    connection = DB_Connect()
    con = connection.getCon()
    connected = connection.isConnected()

    ui = Ui_Form(con, connected, "scott")
    ui.setupUi(ui)
    ui.show()
    sys.exit(app.exec_())
'''